DROP TABLE IF EXISTS Dengue_records;

CREATE TABLE Dengue_records(
    DATE_POSTIVE DATE,
    IC TEXT,
    LOCAL_LSI_ROF TEXT,
    LSI_ROF_NO TEXT,
    BARANGAY TEXT,
    AGE INTEGER,
    GENDER TEXT,
    Number INTEGER,
    STATUS TEXT,
    REMARKS DATE,
    PLACE_OF_ISOLATION TEXT,
    VACCINE TEXT,
    PARTIAL_FULLY_VACCINATED TEXT,
    DATE_OF_LAST_DOSE TEXT,
    DATE_SWAB TEXT
);

select * FROM Dengue_records;


SELECT BARANGAY, COUNT(*) AS total_patients
FROM covid_records
GROUP BY BARANGAY;

